package mmdbwriter

import (
	"reflect"

	"github.com/maxmind/mmdbwriter/v2/mmdbtype"
)

type dataMapKey string

type dataMapIdentityKind byte

const (
	dataMapIdentityBytes dataMapIdentityKind = iota
	dataMapIdentityMap
	dataMapIdentitySlice
	dataMapIdentityUint128
)

type dataMapIdentityKey struct {
	ptr  uintptr
	kind dataMapIdentityKind
	size int
}

// Please note, if you change the order of these fields, please check
// alignment as we end up storing quite a few in memory.
type dataMapValue struct {
	data mmdbtype.DataType
	key  dataMapKey

	// Alternatively, we could use a weak map for the data map, but I
	// don't see any very good options at the moment. We should revist
	// if something happens with https://github.com/golang/go/issues/43615
	refCount uint32
}

// dataMap is used to deduplicate data inserted into the tree to reduce
// memory usage using keys generated by keyWriter.
type dataMap struct {
	data              map[dataMapKey]*dataMapValue
	keyWriter         KeyGenerator
	useDataIdentity   bool
	keyByDataIdentity map[dataMapIdentityKey]dataMapKey
}

func newDataMap(keyGenerator KeyGenerator) *dataMap {
	dm := &dataMap{
		data:      map[dataMapKey]*dataMapValue{},
		keyWriter: keyGenerator,
	}
	// Only the default key writer is guaranteed to derive keys from the full
	// value contents. Custom generators may depend on external state or a
	// subset of fields, so identity cache hits could bypass their semantics.
	if _, ok := keyGenerator.(*keyWriter); ok {
		dm.useDataIdentity = true
	}
	return dm
}

// store stores the value in the dataMap and returns the dataMapValue for it.
// If the value is already in the dataMap, the reference count for it is
// incremented.
func (dm *dataMap) store(v mmdbtype.DataType) (*dataMapValue, error) {
	return dm.storeByGeneratedKey(v)
}

func (dm *dataMap) storeWithIdentity(v mmdbtype.DataType) (*dataMapValue, error) {
	if !dm.useDataIdentity {
		return dm.store(v)
	}

	identity, ok := keyIdentity(v)
	if !ok {
		return dm.store(v)
	}

	if key, ok := dm.keyByDataIdentity[identity]; ok {
		dmv, ok := dm.data[key]
		if ok {
			// Only retained values are pinned by dm.data. Equal-but-distinct
			// values can be mutated or collected, so stale identity entries must
			// be discarded instead of treated as hits.
			if retainedIdentity, ok := keyIdentity(dmv.data); ok && retainedIdentity == identity {
				dmv.refCount++
				return dmv, nil
			}
		}
		delete(dm.keyByDataIdentity, identity)
	}

	dmv, err := dm.storeByGeneratedKey(v)
	if err != nil {
		return nil, err
	}
	if dm.keyByDataIdentity == nil {
		dm.keyByDataIdentity = map[dataMapIdentityKey]dataMapKey{}
	}
	// Register only the identity of the retained value. A generated-key dedupe
	// can return an older equal value, whose pointer is the only safe one to
	// cache because dm.data pins it until remove.
	if retainedIdentity, ok := keyIdentity(dmv.data); ok && retainedIdentity == identity {
		dm.keyByDataIdentity[identity] = dmv.key
	}
	return dmv, nil
}

func (dm *dataMap) storeByGeneratedKey(v mmdbtype.DataType) (*dataMapValue, error) {
	key, err := dm.keyWriter.Key(v)
	if err != nil {
		return nil, err
	}

	dmv, ok := dm.data[dataMapKey(key)]
	if !ok {
		dmKey := dataMapKey(key)
		dmv = &dataMapValue{
			key:  dmKey,
			data: v,
		}
		dm.data[dmKey] = dmv
	}

	dmv.refCount++

	return dmv, nil
}

func keyIdentity(v mmdbtype.DataType) (dataMapIdentityKey, bool) {
	switch t := v.(type) {
	case mmdbtype.Bytes:
		if len(t) == 0 {
			return dataMapIdentityKey{kind: dataMapIdentityBytes}, true
		}
		return dataMapIdentityKey{
			ptr:  reflect.ValueOf(t).Pointer(),
			kind: dataMapIdentityBytes,
			size: len(t),
		}, true
	case mmdbtype.Map:
		if t == nil {
			return dataMapIdentityKey{kind: dataMapIdentityMap}, true
		}
		return dataMapIdentityKey{
			ptr:  reflect.ValueOf(t).Pointer(),
			kind: dataMapIdentityMap,
			size: len(t),
		}, true
	case mmdbtype.Slice:
		if len(t) == 0 {
			return dataMapIdentityKey{kind: dataMapIdentitySlice}, true
		}
		return dataMapIdentityKey{
			ptr:  reflect.ValueOf(t).Pointer(),
			kind: dataMapIdentitySlice,
			size: len(t),
		}, true
	case *mmdbtype.Uint128:
		if t == nil {
			return dataMapIdentityKey{}, false
		}
		return dataMapIdentityKey{
			ptr:  reflect.ValueOf(t).Pointer(),
			kind: dataMapIdentityUint128,
		}, true
	default:
		return dataMapIdentityKey{}, false
	}
}

// addRef adds a reference to the value.
func (dm *dataMap) addRef(v *dataMapValue) {
	// This is here mostly so that we don't have to guard against it
	// elsewhere.
	if v == nil {
		return
	}
	v.refCount++
}

// remove removes a reference to the value. If the reference count
// drops to zero, the value is removed from the dataMap.
func (dm *dataMap) remove(v *dataMapValue) {
	// This is here mostly so that we don't have to guard against it
	// elsewhere.
	if v == nil {
		return
	}
	v.refCount--

	if v.refCount == 0 {
		delete(dm.data, v.key)
		if dm.keyByDataIdentity != nil {
			if identity, ok := keyIdentity(v.data); ok {
				delete(dm.keyByDataIdentity, identity)
			}
		}
	}
}
